name: Analysis

on:
  push:
    branches: [main]
    paths:
      - 'analysis/**'
      - '.github/workflows/analysis.yml'
      - '.github/workflows/python-template.yml'
  pull_request:
    branches: [main]
    paths:
      - 'analysis/**'
      - '.github/workflows/analysis.yml'
      - '.github/workflows/python-template.yml'

jobs:
  analysis:
    uses: ./.github/workflows/python-template.yml
    with:
      project_dir: analysis
